### ISSUE TITLE
Concept for logo

### ISSUE THREAD

**Issue by wrightmartin** [jdrever/changethestory.eu#6]
Hi James,

See attached. I've based it on the original drawing, which I loved, I think it would make a great mascot :) I've change it a bit added a globe that they're holding, along with a pose that hopefully works.

I've also done a scaled back version for web and simple print.
[Untitled.pdf](https://github.com/jdrever/changethestory.eu/files/5555945/Untitled.pdf)

**Comment by jdrever** [comment]
Hi Martin,

Thanks for this – really exciting to see it!  I think you’ve done a great job, really takes the spirit of the original and lifts it – thank you.  From a personal point of view, I think Alfie will really like it too!

One thing that both Richard and myself are struggling with a bit is the globe.  There’s a couple of reasons for this.  Firstly, it’s a common trope of environmental campaigning that we’re holding the future of the world in our hands.  That’s an idea we’re quite keen to undermine.  The reality as we’d see it is  more like: if we’re really stupid we may wipe ourselves out at species level and cause a terrible amount of suffering and collateral damage in the process but the earth will almost certainly take that in it’s stride beyond the short term.  Really it’s ourselves we’re trying to save and if anything, the world holds us in its hand.  See https://ecologise.in/2017/12/01/lynn-margulis-1938-2011-gaia-tough-bitch/

Secondly, we’re really keen to not give the young people in the project the impression that, to continue the metaphor, they need to carry the weight of the world.  I think the message is more: our generation and previous generations are responsible for this situation, and at the moment some of us still hold positions of power that may allow the situation to be sorted out.  Given that, what kind of world do you want to live in?

So we were trying to think about what the spaceman should be holding?  What we want to communicate is the combination of new stories and digital means.  Richard suggested a camera.  I was thinking about what kind of story a high tech spaceman might hold without it just being a Kindle (spaceman pencil!?), or the option of not holding anything.  So, we thought we’d ask you the question – any suggestions?  If ideas aren’t flowing, we can also get inspiration from our partners.

Anyway, thanks again – I’m _really_ happy with the overall feel! 😊

James.

**Comment by wrightmartin** [comment]
Thanks James - great feedback and yep I totally agree with you. How about a futuristic ipad and pencil - like's writing the story?

**Comment by jdrever** [comment]
Hi Martin,

Yes I know Richard said in our discussions “not a spaceman with a kindle” (his preference was digital camera) but a genuinely futuristic/different reinvention of a book/pencil _could_ work.

Are you able to give us some alternative versions?

James.

**Comment by wrightmartin** [comment]
![image](https://user-images.githubusercontent.com/2292925/100497375-0de39f80-3153-11eb-96f0-ec0e803ef24c.png)

Something like this? I was considering adding apparatus to the tablet but I doubt that's going to read well when we scale it down?

**Comment by jdrever** [comment]
Hi Martin,

Had some feedback from the partners on the logo:

--there was some discussion around whether the cosmonaut (as we’re now calling her/him!) was male or female – sense that this version of the cosmonaut felt more “male” than the previous one, and I was asked if there was anything we could do make the design more gender-less.  It was felt that the roundedness of the belly was what signified male characteristics, which is interesting!
--request to keep the tablet but lose the pen/stylus – to keep the idea of what a story might be as open as possible.
--some comments about showing a tablet screen to us rather than merely holding it (though that may be a challenge to represent at logo size).  Could be a blank page?
--and a lovely idea of having the earth reflect back in the helmet but again maybe hard to make work at logo size

Let me know what you think about the feedback, I think it would be good to refine /address what can be addressed but I don’t want to prolong the process.

For info – I’ve been working on the code base this week, adding a very rough list of stories/story info page, and starting to develop the Hungarian version of the project website.

Hope you’ve had a good week, and wishing you a good weekend.  We have our two eldest back from their respective unis this weekend, looking forward to that..

James.
